"""
create_video.py - Upgraded with stunning genre-specific visuals using pure FFmpeg.
No external APIs needed - everything generated by FFmpeg filters.
"""

import subprocess
import json
import sys
import os
from pathlib import Path
from datetime import datetime

WIDTH = 1920
HEIGHT = 1080
FPS = 30


# Genre-specific visual configs
# Each has: filter (FFmpeg lavfi expression), wave_color, text_color, accent_color
GENRE_VISUALS = {
    "blues": {
        "bg": f"color=c=0x020818:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W+T*0.15))*40+sin(2*PI*(Y/H+T*0.08))*30+10,0,255)':g='clip(sin(2*PI*(X/W+T*0.12))*20+sin(2*PI*(Y/H+T*0.06))*15+5,0,255)':b='clip(sin(2*PI*(X/W+T*0.2))*80+sin(2*PI*(Y/H+T*0.1))*60+30,0,255)'",
        "wave": "4488ff|224488", "text": "cce0ff", "accent": "4488ff",
    },
    "jazz": {
        "bg": f"color=c=0x120800:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*2+T*0.3))*80+sin(2*PI*(Y/H+T*0.15))*40+60,0,255)':g='clip(sin(2*PI*(X/W+T*0.2))*40+sin(2*PI*(Y/H*2+T*0.1))*20+20,0,255)':b='clip(sin(2*PI*(X/W+T*0.1))*20+10,0,255)'",
        "wave": "ff9933|cc7722", "text": "ffe0b0", "accent": "ff9933",
    },
    "kpop": {
        "bg": f"color=c=0x0d0015:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*3+T*0.5))*120+sin(2*PI*(Y/H*2+T*0.3))*60+40,0,255)':g='clip(sin(2*PI*(X/W*2+T*0.4))*80+sin(2*PI*(Y/H*3+T*0.2))*40+10,0,255)':b='clip(sin(2*PI*(X/W*4+T*0.6))*140+sin(2*PI*(Y/H*2+T*0.4))*70+50,0,255)'",
        "wave": "ff44ff|aa00ff", "text": "ffccff", "accent": "ff44ff",
    },
    "classical": {
        "bg": f"color=c=0x080808:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W+T*0.05))*30+sin(2*PI*(Y/H+T*0.03))*20+15,0,255)':g='clip(sin(2*PI*(X/W+T*0.04))*28+sin(2*PI*(Y/H+T*0.025))*18+14,0,255)':b='clip(sin(2*PI*(X/W+T*0.06))*25+sin(2*PI*(Y/H+T*0.04))*15+12,0,255)'",
        "wave": "e8d5a0|c4a96e", "text": "fff8e7", "accent": "e8d5a0",
    },
    "hiphop": {
        "bg": f"color=c=0x050505:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*5+T*0.8))*100+sin(2*PI*(Y/H*3+T*0.5))*50+30,0,255)':g='clip(sin(2*PI*(X/W*4+T*0.6))*30+10,0,255)':b='clip(sin(2*PI*(X/W*3+T*0.4))*15+5,0,255)'",
        "wave": "ff4444|ff8800", "text": "ffffff", "accent": "ff4444",
    },
    "ambient": {
        "bg": f"color=c=0x001510:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*0.5+T*0.06))*20+sin(2*PI*(Y/H*0.3+T*0.04))*15+5,0,255)':g='clip(sin(2*PI*(X/W*0.4+T*0.05))*60+sin(2*PI*(Y/H*0.5+T*0.03))*40+20,0,255)':b='clip(sin(2*PI*(X/W*0.6+T*0.07))*50+sin(2*PI*(Y/H*0.4+T*0.05))*35+15,0,255)'",
        "wave": "44ffcc|00ccaa", "text": "ccffee", "accent": "44ffcc",
    },
    "rock": {
        "bg": f"color=c=0x100000:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*4+T*0.7))*140+sin(2*PI*(Y/H*3+T*0.5))*80+50,0,255)':g='clip(sin(2*PI*(X/W*3+T*0.5))*30+sin(2*PI*(Y/H*2+T*0.3))*15+10,0,255)':b='clip(sin(2*PI*(X/W*2+T*0.3))*10+5,0,255)'",
        "wave": "ff2200|ff6600", "text": "ffffff", "accent": "ff2200",
    },
    "gospel": {
        "bg": f"color=c=0x100f00:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*0.8+T*0.1))*100+sin(2*PI*(Y/H*0.6+T*0.07))*60+80,0,255)':g='clip(sin(2*PI*(X/W*0.7+T*0.09))*80+sin(2*PI*(Y/H*0.5+T*0.06))*50+60,0,255)':b='clip(sin(2*PI*(X/W*0.5+T*0.07))*20+sin(2*PI*(Y/H*0.4+T*0.05))*15+5,0,255)'",
        "wave": "ffee44|ffcc00", "text": "fffff0", "accent": "ffcc00",
    },
    "cinematic": {
        "bg": f"color=c=0x000510:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*0.3+T*0.04))*15+sin(2*PI*(Y/H*0.2+T*0.03))*10+5,0,255)':g='clip(sin(2*PI*(X/W*0.4+T*0.05))*20+sin(2*PI*(Y/H*0.3+T*0.04))*12+8,0,255)':b='clip(sin(2*PI*(X/W*0.5+T*0.06))*80+sin(2*PI*(Y/H*0.4+T*0.05))*50+30,0,255)'",
        "wave": "4488ff|0044cc", "text": "cce0ff", "accent": "4488ff",
    },
    "lofi": {
        "bg": f"color=c=0x080810:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*0.6+T*0.08))*30+sin(2*PI*(Y/H*0.4+T*0.05))*20+15,0,255)':g='clip(sin(2*PI*(X/W*0.5+T*0.07))*28+sin(2*PI*(Y/H*0.5+T*0.04))*18+14,0,255)':b='clip(sin(2*PI*(X/W*0.7+T*0.09))*50+sin(2*PI*(Y/H*0.6+T*0.06))*30+20,0,255)'",
        "wave": "99aacc|667799", "text": "dde0ee", "accent": "99aacc",
    },
    "afrobeat": {
        "bg": f"color=c=0x0a0500:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*3+T*0.6))*120+sin(2*PI*(Y/H*2+T*0.4))*60+50,0,255)':g='clip(sin(2*PI*(X/W*2+T*0.4))*60+sin(2*PI*(Y/H*3+T*0.3))*30+20,0,255)':b='clip(sin(2*PI*(X/W*1+T*0.2))*15+5,0,255)'",
        "wave": "ff8833|ff4400", "text": "ffe0cc", "accent": "ff8833",
    },
    "latin": {
        "bg": f"color=c=0x100500:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*2+T*0.4))*100+sin(2*PI*(Y/H*3+T*0.3))*60+50,0,255)':g='clip(sin(2*PI*(X/W*3+T*0.5))*80+sin(2*PI*(Y/H*2+T*0.35))*40+30,0,255)':b='clip(sin(2*PI*(X/W*1+T*0.2))*20+5,0,255)'",
        "wave": "ff6633|ffcc00", "text": "ffe8cc", "accent": "ffcc00",
    },
    "edm": {
        "bg": f"color=c=0x000a15:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*6+T*1.0))*80+sin(2*PI*(Y/H*4+T*0.7))*40+20,0,255)':g='clip(sin(2*PI*(X/W*5+T*0.8))*100+sin(2*PI*(Y/H*5+T*0.6))*50+30,0,255)':b='clip(sin(2*PI*(X/W*4+T*0.9))*140+sin(2*PI*(Y/H*3+T*0.8))*70+40,0,255)'",
        "wave": "00ffff|ff00ff", "text": "ccffff", "accent": "00ffff",
    },
    "rnb": {
        "bg": f"color=c=0x100008:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*2+T*0.3))*90+sin(2*PI*(Y/H*2+T*0.2))*45+40,0,255)':g='clip(sin(2*PI*(X/W*1.5+T*0.2))*20+sin(2*PI*(Y/H*1+T*0.15))*10+5,0,255)':b='clip(sin(2*PI*(X/W*2.5+T*0.4))*60+sin(2*PI*(Y/H*2+T*0.25))*30+20,0,255)'",
        "wave": "ff44aa|cc0066", "text": "ffccee", "accent": "ff44aa",
    },
    "folk": {
        "bg": f"color=c=0x0a0800:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W*0.7+T*0.09))*60+sin(2*PI*(Y/H*0.5+T*0.06))*40+30,0,255)':g='clip(sin(2*PI*(X/W*0.6+T*0.08))*50+sin(2*PI*(Y/H*0.6+T*0.05))*35+25,0,255)':b='clip(sin(2*PI*(X/W*0.4+T*0.06))*15+8,0,255)'",
        "wave": "ccaa44|997733", "text": "fff0cc", "accent": "ccaa44",
    },
    "default": {
        "bg": f"color=c=0x0a0a1a:s={WIDTH}x{HEIGHT}:r={FPS}[base];[base]geq=r='clip(sin(2*PI*(X/W+T*0.15))*40+sin(2*PI*(Y/H+T*0.1))*25+15,0,255)':g='clip(sin(2*PI*(X/W+T*0.12))*35+sin(2*PI*(Y/H+T*0.08))*22+12,0,255)':b='clip(sin(2*PI*(X/W+T*0.18))*80+sin(2*PI*(Y/H+T*0.12))*50+30,0,255)'",
        "wave": "7f77dd|5dcaa5", "text": "eeedfe", "accent": "7f77dd",
    },
}


def get_visual(genre: str) -> dict:
    key = genre.lower().replace(" ", "").replace("-", "").replace("_", "")
    # Try exact match first, then partial
    for k in GENRE_VISUALS:
        if k == key or key.startswith(k) or k.startswith(key[:4]):
            return GENRE_VISUALS[k]
    return GENRE_VISUALS["default"]


def find_blueprint(mp3_path: Path) -> dict:
    stem = mp3_path.stem
    # Queue dir could be 2 levels up (music/genre/file) or 1 level (music/file)
    for queue_dir in [mp3_path.parent.parent.parent / "queue", mp3_path.parent.parent / "queue"]:
        if queue_dir.exists():
            exact = queue_dir / f"{stem}.json"
            if exact.exists():
                with open(exact) as f:
                    return json.load(f)
            blueprints = sorted(queue_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
            for bp in blueprints:
                if not (bp.parent / f"processed_{bp.name}").exists():
                    with open(bp) as f:
                        return json.load(f)
                    break

    # Fallback: infer genre from parent folder name
    genre = mp3_path.parent.name.title()
    if genre.lower() in ["music", ""]:
        genre = "Music"
    track_name = stem.replace("-", " ").replace("_", " ").title()
    print(f"No blueprint - fallback genre: {genre}")
    return {
        "genre": genre,
        "title": f"{track_name} — Goosebumps Music",
        "frisson_score": 82,
        "scientific_note": "Engineered using the neuroscience of frisson to trigger goosebumps.",
        "description": (
            f"{track_name} is crafted to give you chills using the science of musical frisson.\n\n"
            "Our tracks use unexpected harmonic shifts, dynamic contrast, and melodic tension — "
            "all proven to trigger dopamine release and the physical sensation of goosebumps.\n\n"
            "Subscribe to the Goosebumps Channel for more frisson-engineered music."
        ),
        "tags": ["goosebumps", "frisson", genre.lower(), "royalty free music", "chills"],
    }


def get_audio_duration(mp3_path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(mp3_path)],
        capture_output=True, text=True
    )
    return float(result.stdout.strip())


def esc(text):
    return str(text).replace("'", "").replace(":", " ").replace(",", " ").replace("[", "").replace("]", "").replace("\\", "")


def create_video(mp3_path: Path, output_dir: Path):
    mp3_path = Path(mp3_path)
    blueprint = find_blueprint(mp3_path)

    genre = blueprint.get("genre", "Music")
    title = blueprint.get("title", "Goosebumps Music")
    scientific_note = blueprint.get("scientific_note", "Engineered using the neuroscience of frisson to trigger goosebumps.")
    frisson_score = blueprint.get("frisson_score", "")

    duration = get_audio_duration(mp3_path)
    visual = get_visual(genre)
    wave1, wave2 = visual["wave"].split("|")
    text_color = visual["text"]
    accent = visual["accent"]

    output_dir.mkdir(exist_ok=True, parents=True)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    genre_slug = genre.lower().replace(" ", "_").replace("-", "_")
    output_path = output_dir / f"{timestamp}_{genre_slug}.mp4"

    title_esc = esc(title[:55] + "..." if len(str(title)) > 55 else title)
    genre_esc = esc(genre.upper())
    note_esc = esc(scientific_note[:85] + "..." if len(str(scientific_note)) > 85 else scientific_note)
    score_text = esc(f"Frisson Score  {frisson_score}%") if frisson_score else ""

    font_bold = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    font_reg = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    font_ital = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf"

    # Build the filter graph:
    # 1. Animated color background (genre-specific plasma waves)
    # 2. Waveform overlay (thinner, more elegant)
    # 3. Gradient vignette for depth
    # 4. Text overlays with fade-in

    bg_filter = visual["bg"]

    filter_complex = (
        # Generate animated background
        f"color=c=black:s={WIDTH}x{HEIGHT}:r={FPS}[black];"
        f"{bg_filter}[bg_raw];"

        # Waveform from audio - thinner elegant line
        f"[0:a]showwaves=s={WIDTH}x{HEIGHT//5}:mode=cline:rate={FPS}"
        f":colors=#{wave1}@0.9|#{wave2}@0.7[wave];"

        # Overlay wave on background at center-bottom area
        f"[bg_raw][wave]overlay=0:{int(HEIGHT*0.62)}:format=auto[with_wave];"

        # Title text
        f"[with_wave]drawtext=fontfile={font_bold}"
        f":text='{title_esc}'"
        f":fontcolor=#{text_color}"
        f":fontsize=56"
        f":x=(w-text_w)/2:y=h*0.10"
        f":alpha='if(lt(t,1.5),t/1.5,1)'"
        f":shadowcolor=black@0.8:shadowx=3:shadowy=3[t1];"

        # Genre badge
        f"[t1]drawtext=fontfile={font_reg}"
        f":text='{genre_esc}'"
        f":fontcolor=#{accent}"
        f":fontsize=24"
        f":x=(w-text_w)/2:y=h*0.21"
        f":alpha='if(lt(t,2),t/2,1)'"
        f":shadowcolor=black@0.9:shadowx=2:shadowy=2[t2];"

        # Scientific note at bottom
        f"[t2]drawtext=fontfile={font_ital}"
        f":text='{note_esc}'"
        f":fontcolor=#{text_color}@0.85"
        f":fontsize=22"
        f":x=(w-text_w)/2:y=h*0.89"
        f":alpha='if(lt(t,3),t/3,1)'"
        f":shadowcolor=black@0.9:shadowx=2:shadowy=2[t3];"

        # Channel watermark
        f"[t3]drawtext=fontfile={font_bold}"
        f":text='GOOSEBUMPS'"
        f":fontcolor=#{accent}@0.7"
        f":fontsize=16"
        f":x=w-text_w-30:y=28"
        f":shadowcolor=black@0.8:shadowx=1:shadowy=1[final]"
    )

    # Add frisson score if available
    if score_text:
        filter_complex = filter_complex.replace(
            "[final]",
            f"[pre_score];[pre_score]drawtext=fontfile={font_reg}"
            f":text='{score_text}'"
            f":fontcolor=#{wave1}@0.85"
            f":fontsize=18:x=28:y=28"
            f":shadowcolor=black@0.8:shadowx=1:shadowy=1[final]"
        )

    cmd = [
        "ffmpeg", "-y",
        "-i", str(mp3_path),
        "-filter_complex", filter_complex,
        "-map", "[final]",
        "-map", "0:a",
        "-c:v", "libx264", "-preset", "fast", "-crf", "20",
        "-c:a", "aac", "-b:a", "192k",
        "-t", str(duration),
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        str(output_path)
    ]

    print(f"Creating: {output_path.name} | {genre} | {duration:.1f}s")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("FFmpeg error:")
        print(result.stderr[-3000:])
        raise RuntimeError("FFmpeg failed")

    print(f"Video created: {output_path}")
    return output_path, blueprint


def main():
    mp3_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("")

    if not mp3_path.name or not mp3_path.suffix:
        music_dir = Path(__file__).parent.parent / "music"
        mp3s = sorted(music_dir.rglob("*.mp3"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not mp3s:
            print("No MP3 files found in music/ folder")
            sys.exit(1)
        mp3_path = mp3s[0]
        print(f"Auto-detected: {mp3_path}")

    if not mp3_path.exists():
        repo_root = Path(__file__).parent.parent
        mp3_path = repo_root / mp3_path
        if not mp3_path.exists():
            print(f"File not found: {mp3_path}")
            sys.exit(1)

    output_dir = Path(__file__).parent.parent / "output"
    video_path, blueprint = create_video(mp3_path, output_dir)

    state_path = output_dir / f"{video_path.stem}_state.json"
    with open(state_path, "w") as f:
        json.dump({"video_path": str(video_path), "mp3_path": str(mp3_path), "blueprint": blueprint}, f, indent=2)

    print(f"State saved: {state_path}")
    print("Ready for upload.")


if __name__ == "__main__":
    main()