"""
create_video.py - Genre-specific animated visuals using pure FFmpeg.
No external APIs - everything generated by FFmpeg filters.
"""

import subprocess
import json
import sys
from pathlib import Path
from datetime import datetime

WIDTH = 1920
HEIGHT = 1080
FPS = 30

GENRE_THEMES = {
    "blues":     {"wave":"4488ff|224488","text":"cce0ff","accent":"4488ff","r":"10","g":"5","b":"80"},
    "jazz":      {"wave":"ff9933|cc7722","text":"ffe0b0","accent":"ff9933","r":"80","g":"30","b":"5"},
    "kpop":      {"wave":"ff44ff|aa00ff","text":"ffccff","accent":"ff44ff","r":"100","g":"20","b":"120"},
    "classical": {"wave":"e8d5a0|c4a96e","text":"fff8e7","accent":"e8d5a0","r":"25","g":"22","b":"18"},
    "hiphop":    {"wave":"ff4444|ff8800","text":"ffffff","accent":"ff4444","r":"80","g":"10","b":"5"},
    "ambient":   {"wave":"44ffcc|00ccaa","text":"ccffee","accent":"44ffcc","r":"5","g":"50","b":"40"},
    "rock":      {"wave":"ff2200|ff6600","text":"ffffff","accent":"ff2200","r":"120","g":"15","b":"5"},
    "gospel":    {"wave":"ffee44|ffcc00","text":"fffff0","accent":"ffcc00","r":"100","g":"80","b":"5"},
    "cinematic": {"wave":"4488ff|0044cc","text":"cce0ff","accent":"4488ff","r":"5","g":"8","b":"70"},
    "lofi":      {"wave":"99aacc|667799","text":"dde0ee","accent":"99aacc","r":"20","g":"18","b":"40"},
    "afrobeat":  {"wave":"ff8833|ff4400","text":"ffe0cc","accent":"ff8833","r":"100","g":"40","b":"5"},
    "latin":     {"wave":"ff6633|ffcc00","text":"ffe8cc","accent":"ffcc00","r":"90","g":"60","b":"5"},
    "edm":       {"wave":"00ffff|ff00ff","text":"ccffff","accent":"00ffff","r":"20","g":"80","b":"120"},
    "rnb":       {"wave":"ff44aa|cc0066","text":"ffccee","accent":"ff44aa","r":"80","g":"10","b":"50"},
    "folk":      {"wave":"ccaa44|997733","text":"fff0cc","accent":"ccaa44","r":"55","g":"45","b":"8"},
    "celtic":    {"wave":"44cc88|009944","text":"ccffdd","accent":"44cc88","r":"10","g":"60","b":"20"},
    "indian":    {"wave":"ff6600|ffcc00","text":"ffe8cc","accent":"ff6600","r":"90","g":"50","b":"5"},
    "electronic":{"wave":"00ffff|0088ff","text":"ccffff","accent":"00ffff","r":"5","g":"60","b":"100"},
    "country":   {"wave":"ddaa44|aa7722","text":"fff0cc","accent":"ddaa44","r":"60","g":"45","b":"8"},
    "metal":     {"wave":"ff2200|880000","text":"ffffff","accent":"ff2200","r":"100","g":"5","b":"5"},
    "reggae":    {"wave":"44ff44|ffee00","text":"ccffcc","accent":"44ff44","r":"10","g":"80","b":"10"},
    "world":     {"wave":"dd88ff|8833cc","text":"eeccff","accent":"dd88ff","r":"60","g":"20","b":"80"},
    "indie":     {"wave":"ff8866|cc4422","text":"ffe0d0","accent":"ff8866","r":"70","g":"30","b":"15"},
    "neosoul":   {"wave":"ff88aa|cc4466","text":"ffddee","accent":"ff88aa","r":"80","g":"20","b":"50"},
    "flamenco":  {"wave":"ff3300|ffaa00","text":"ffe8cc","accent":"ff3300","r":"100","g":"30","b":"5"},
    "default":   {"wave":"7f77dd|5dcaa5","text":"eeedfe","accent":"7f77dd","r":"30","g":"25","b":"70"},
}


def get_theme(genre: str) -> dict:
    key = genre.lower().replace(" ", "").replace("-", "").replace("_", "")
    for k in GENRE_THEMES:
        if key == k or key.startswith(k[:4]) or k.startswith(key[:4]):
            return GENRE_THEMES[k]
    return GENRE_THEMES["default"]


def find_blueprint(mp3_path: Path) -> dict:
    for queue_dir in [
        mp3_path.parent.parent.parent / "queue",
        mp3_path.parent.parent / "queue",
    ]:
        if queue_dir.exists():
            blueprints = sorted(queue_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
            for bp in blueprints:
                if not (bp.parent / f"processed_{bp.name}").exists():
                    with open(bp) as f:
                        return json.load(f)

    genre = mp3_path.parent.name.title()
    if genre.lower() in ["music", ""]:
        genre = "Music"
    track_name = mp3_path.stem.encode("ascii", "ignore").decode().replace("-", " ").replace("_", " ").strip() or "Goosebumps Track"
    print(f"No blueprint - fallback genre: {genre}")
    return {
        "genre": genre,
        "title": f"{track_name} - Goosebumps Music",
        "frisson_score": 82,
        "scientific_note": "Engineered using the neuroscience of frisson to trigger goosebumps.",
        "description": (
            f"{track_name} is crafted to give you chills using the science of musical frisson.\n\n"
            "Our tracks use unexpected harmonic shifts, dynamic contrast, and melodic tension — "
            "all proven to trigger dopamine release and the physical sensation of goosebumps.\n\n"
            "Subscribe to the Goosebumps Channel for more frisson-engineered music."
        ),
        "tags": ["goosebumps", "frisson", genre.lower(), "royalty free music", "chills"],
    }


def get_audio_duration(mp3_path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(mp3_path)],
        capture_output=True, text=True
    )
    return float(result.stdout.strip())


def safe_text(text: str, max_len: int = 55) -> str:
    """Strip non-ASCII and special chars that break FFmpeg drawtext."""
    cleaned = text.encode("ascii", "ignore").decode().strip()
    cleaned = cleaned.replace("'", "").replace('"', "").replace(":", " ").replace(",", " ")
    cleaned = cleaned.replace("[", "").replace("]", "").replace("\\", "").replace("%", "")
    if len(cleaned) > max_len:
        cleaned = cleaned[:max_len] + "..."
    return cleaned or "Goosebumps Music"


def create_video(mp3_path: Path, output_dir: Path):
    mp3_path = Path(mp3_path)
    blueprint = find_blueprint(mp3_path)

    genre = blueprint.get("genre", "Music")
    title = safe_text(blueprint.get("title", "Goosebumps Music"))
    note = safe_text(blueprint.get("scientific_note", "Engineered using the neuroscience of frisson to trigger goosebumps."), 90)
    frisson_score = blueprint.get("frisson_score", "")
    score_text = safe_text(f"Frisson Score  {frisson_score}%") if frisson_score else ""

    duration = get_audio_duration(mp3_path)
    theme = get_theme(genre)
    w1, w2 = theme["wave"].split("|")
    tc = theme["text"]
    ac = theme["accent"]
    r, g, b = theme["r"], theme["g"], theme["b"]

    output_dir.mkdir(exist_ok=True, parents=True)
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    slug = genre.lower().replace(" ", "_")[:12]
    output_path = output_dir / f"{ts}_{slug}.mp4"

    font_bold = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    font_reg  = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    font_ital = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf"

    genre_upper = safe_text(genre.upper(), 20)

    # Build filter — animated plasma BG + waveform + text
    # Using lavfi color source fed into geq for animated plasma
    filter_complex = (
        # Animated background via geq on a solid color source
        f"color=c=black:s={WIDTH}x{HEIGHT}:r={FPS},"
        f"geq="
        f"r='clip({r}+sin(2*PI*(X/{WIDTH}*2+T*0.15))*60+sin(2*PI*(Y/{HEIGHT}+T*0.1))*30,0,255)':"
        f"g='clip({g}+sin(2*PI*(X/{WIDTH}+T*0.12))*40+sin(2*PI*(Y/{HEIGHT}*2+T*0.08))*20,0,255)':"
        f"b='clip({b}+sin(2*PI*(X/{WIDTH}*1.5+T*0.2))*80+sin(2*PI*(Y/{HEIGHT}*1.5+T*0.15))*50,0,255)'"
        f"[bg];"

        # Waveform
        f"[0:a]showwaves=s={WIDTH}x{HEIGHT//5}:mode=cline:rate={FPS}"
        f":colors=#{w1}@0.9|#{w2}@0.7[wave];"

        # Overlay wave on background
        f"[bg][wave]overlay=0:{int(HEIGHT*0.62)}:format=auto[v1];"

        # Title
        f"[v1]drawtext=fontfile={font_bold}:text='{title}'"
        f":fontcolor=#{tc}:fontsize=54:x=(w-text_w)/2:y=h*0.10"
        f":alpha='if(lt(t\\,1.5)\\,t/1.5\\,1)':shadowcolor=black@0.8:shadowx=3:shadowy=3[v2];"

        # Genre
        f"[v2]drawtext=fontfile={font_reg}:text='{genre_upper}'"
        f":fontcolor=#{ac}:fontsize=24:x=(w-text_w)/2:y=h*0.21"
        f":alpha='if(lt(t\\,2)\\,t/2\\,1)':shadowcolor=black@0.9:shadowx=2:shadowy=2[v3];"

        # Scientific note
        f"[v3]drawtext=fontfile={font_ital}:text='{note}'"
        f":fontcolor=#{tc}@0.85:fontsize=22:x=(w-text_w)/2:y=h*0.89"
        f":alpha='if(lt(t\\,3)\\,t/3\\,1)':shadowcolor=black@0.9:shadowx=2:shadowy=2[v4];"

        # Watermark
        f"[v4]drawtext=fontfile={font_bold}:text='GOOSEBUMPS'"
        f":fontcolor=#{ac}@0.7:fontsize=16:x=w-text_w-30:y=28"
        f":shadowcolor=black@0.8:shadowx=1:shadowy=1[vout]"
    )

    # Add score if available
    if score_text:
        filter_complex = filter_complex.replace(
            "[vout]",
            f"[vpre];[vpre]drawtext=fontfile={font_reg}:text='{score_text}'"
            f":fontcolor=#{w1}@0.85:fontsize=18:x=28:y=28"
            f":shadowcolor=black@0.8:shadowx=1:shadowy=1[vout]"
        )

    cmd = [
        "ffmpeg", "-y",
        "-i", str(mp3_path),
        "-filter_complex", filter_complex,
        "-map", "[vout]",
        "-map", "0:a",
        "-c:v", "libx264", "-preset", "fast", "-crf", "20",
        "-c:a", "aac", "-b:a", "192k",
        "-t", str(duration),
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        str(output_path)
    ]

    print(f"Creating: {output_path.name} | {genre} | {duration:.1f}s")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("FFmpeg stderr (last 2000 chars):")
        print(result.stderr[-2000:])
        raise RuntimeError("FFmpeg failed")

    print(f"Video created: {output_path}")
    return output_path, blueprint


def main():
    mp3_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("")

    if not mp3_path.name or not mp3_path.suffix:
        music_dir = Path(__file__).parent.parent / "music"
        mp3s = sorted(music_dir.rglob("*.mp3"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not mp3s:
            print("No MP3 files found in music/ folder")
            raise SystemExit(1)
        mp3_path = mp3s[0]
        print(f"Auto-detected: {mp3_path}")

    if not mp3_path.exists():
        repo_root = Path(__file__).parent.parent
        alt = repo_root / mp3_path
        if alt.exists():
            mp3_path = alt
        else:
            print(f"File not found: {mp3_path}")
            raise SystemExit(1)

    output_dir = Path(__file__).parent.parent / "output"
    video_path, blueprint = create_video(mp3_path, output_dir)

    state_path = output_dir / f"{video_path.stem}_state.json"
    with open(state_path, "w") as f:
        json.dump({"video_path": str(video_path), "mp3_path": str(mp3_path), "blueprint": blueprint}, f, indent=2)

    print(f"State: {state_path}")
    print("Ready for upload.")


if __name__ == "__main__":
    main()